[workspace]
members = [
    "bins/revme",
    "bins/revm-test",
    "crates/revm",
    "crates/primitives",
    "crates/interpreter",
    "crates/precompile",
]
resolver = "2"
default-members = ["crates/revm"]

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace.dependencies]
# openvm
openvm = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-ecc-guest = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-pairing-guest = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-keccak256-guest = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-sha256-guest = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-sdk = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-build = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-pairing-transpiler = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-rv32im-transpiler = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-transpiler = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-algebra-circuit = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-algebra-transpiler = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-ecc-circuit = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-ecc-transpiler = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-pairing-circuit = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-circuit = { git = "https://github.com/openvm-org/openvm.git", branch = "main" }
openvm-stark-sdk = { git = "https://github.com/openvm-org/stark-backend.git", branch = "main" }

[profile.release]
lto = true
codegen-units = 1
debug = true

[profile.ethtests]
inherits = "test"
opt-level = 3

[patch.crates-io]
ff = { git = "https://github.com/scroll-tech/ff", branch = "feat/sp1" }

alloy-eips = { git = "https://github.com/scroll-tech/alloy.git", branch = "v0.5.4" }

alloy-eip2930 = { git = "https://github.com/scroll-tech/alloy-eips", branch = "v0.4.2" }
alloy-eip7702 = { git = "https://github.com/scroll-tech/alloy-eips", branch = "v0.4.2" }

alloy-primitives = { git = "https://github.com/scroll-tech/alloy-core", branch = "v0.8.14" }
alloy-sol-types = { git = "https://github.com/scroll-tech/alloy-core", branch = "v0.8.14" }
