name: Tests

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches: [ main, "release/**", "scroll-evm-executor/**" ]
  pull_request:
    branches: [ main, "release/**", "scroll-evm-executor/**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test ${{ matrix.rust }} ${{ matrix.flags }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        rust: [ "stable", "beta", "nightly" ]
        flags: [
          "--no-default-features",
          "",
          "--features=\"scroll\"",
          "--features=\"scroll, scroll-poseidon-codehash\"",
          "--features=\"all, scroll\"",
          "--features=\"all, scroll, scroll-poseidon-codehash\"",
          "--features=\"optimism\""
          "--features=\"all, optimism\""
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --workspace ${{ matrix.flags }}

  check-no-std:
    name: check no_std ${{ matrix.features }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        features: [ "", "optimism" ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv32imac-unknown-none-elf
      - run: cargo check --target riscv32imac-unknown-none-elf --no-default-features --features=${{ matrix.features }}

  check:
    name: check ${{ matrix.features }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        features: [ "", "serde", "std" ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --no-default-features -p revm  --features=${{ matrix.features }}

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy --workspace --all-targets --features all,scroll
        env:
          RUSTFLAGS: -Dwarnings
      - run: cargo clippy --workspace --all-targets --features all,optimism

  docs:
    name: docs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-docs
      - run: cargo doc --workspace --features all,scroll --no-deps --document-private-items
        env:
          RUSTDOCFLAGS: "--cfg docsrs -D warnings"

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all --check
